/**
 * Shipment Tracking API
 * Shipment Tracking Management provides operations to track shipments.
 *
 * The version of the OpenAPI document: 1.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrderRefType model module.
 * @module model/OrderRefType
 * @version 1.14.0
 */
class OrderRefType {
    /**
     * Constructs a new <code>OrderRefType</code>.
     * Reference to an order that can typically be queried with another API
     * @alias module:model/OrderRefType
     */
    constructor() { 
        
        OrderRefType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderRefType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderRefType} obj Optional instance to populate.
     * @return {module:model/OrderRefType} The populated <code>OrderRefType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderRefType();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('href')) {
                obj['href'] = ApiClient.convertToType(data['href'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('referredType')) {
                obj['referredType'] = ApiClient.convertToType(data['referredType'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrderRefType</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrderRefType</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['href'] && !(typeof data['href'] === 'string' || data['href'] instanceof String)) {
            throw new Error("Expected the field `href` to be a primitive type in the JSON string but got " + data['href']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['referredType'] && !(typeof data['referredType'] === 'string' || data['referredType'] instanceof String)) {
            throw new Error("Expected the field `referredType` to be a primitive type in the JSON string but got " + data['referredType']);
        }

        return true;
    }


}



/**
 * Unique identifier of the order
 * @member {String} id
 */
OrderRefType.prototype['id'] = undefined;

/**
 * URI where to query or perform actions on the order
 * @member {String} href
 */
OrderRefType.prototype['href'] = undefined;

/**
 * Screen name of the order
 * @member {String} name
 */
OrderRefType.prototype['name'] = undefined;

/**
 * Type of the referred order in case it is polymorphic
 * @member {String} referredType
 */
OrderRefType.prototype['referredType'] = undefined;






export default OrderRefType;

