/**
 * Shipment Tracking API
 * Shipment Tracking Management provides operations to track shipments.
 *
 * The version of the OpenAPI document: 1.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Address from './model/Address';
import CustomerRefType from './model/CustomerRefType';
import Error from './model/Error';
import OrderRefType from './model/OrderRefType';
import ShipmentTracking from './model/ShipmentTracking';
import ShipmentTrackingApi from './api/ShipmentTrackingApi';


/**
* Shipment Tracking Management provides operations to track shipments..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ShipmentTrackingApi = require('index'); // See note below*.
* var xxxSvc = new ShipmentTrackingApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ShipmentTrackingApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ShipmentTrackingApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ShipmentTrackingApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.14.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Address model constructor.
     * @property {module:model/Address}
     */
    Address,

    /**
     * The CustomerRefType model constructor.
     * @property {module:model/CustomerRefType}
     */
    CustomerRefType,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The OrderRefType model constructor.
     * @property {module:model/OrderRefType}
     */
    OrderRefType,

    /**
     * The ShipmentTracking model constructor.
     * @property {module:model/ShipmentTracking}
     */
    ShipmentTracking,

    /**
    * The ShipmentTrackingApi service constructor.
    * @property {module:api/ShipmentTrackingApi}
    */
    ShipmentTrackingApi
};
