/**
 * Shipment Tracking API
 * Shipment Tracking Management provides operations to track shipments.
 *
 * The version of the OpenAPI document: 1.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ShipmentTrackingApi);
  }
}(this, function(expect, ShipmentTrackingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ShipmentTrackingApi.ShipmentTrackingApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ShipmentTrackingApi', function() {
    describe('getShipmentTracking', function() {
      it('should call getShipmentTracking successfully', function(done) {
        //uncomment below and update the code to test getShipmentTracking
        //instance.getShipmentTracking(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getShipmentTrackingByTrackingId', function() {
      it('should call getShipmentTrackingByTrackingId successfully', function(done) {
        //uncomment below and update the code to test getShipmentTrackingByTrackingId
        //instance.getShipmentTrackingByTrackingId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchShipmentTrackingUsingPATCH', function() {
      it('should call patchShipmentTrackingUsingPATCH successfully', function(done) {
        //uncomment below and update the code to test patchShipmentTrackingUsingPATCH
        //instance.patchShipmentTrackingUsingPATCH(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postShipmentTracking', function() {
      it('should call postShipmentTracking successfully', function(done) {
        //uncomment below and update the code to test postShipmentTracking
        //instance.postShipmentTracking(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
