/**
 * Shipment Tracking API
 * Shipment Tracking Management provides operations to track shipments.
 *
 * The version of the OpenAPI document: 1.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ShipmentTrackingApi);
  }
}(this, function(expect, ShipmentTrackingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ShipmentTrackingApi.Address();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Address', function() {
    it('should create an instance of Address', function() {
      // uncomment below and update the code to test Address
      //var instance = new ShipmentTrackingApi.Address();
      //expect(instance).to.be.a(ShipmentTrackingApi.Address);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ShipmentTrackingApi.Address();
      //expect(instance).to.be();
    });

    it('should have the property streetNr (base name: "streetNr")', function() {
      // uncomment below and update the code to test the property streetNr
      //var instance = new ShipmentTrackingApi.Address();
      //expect(instance).to.be();
    });

    it('should have the property streetName (base name: "streetName")', function() {
      // uncomment below and update the code to test the property streetName
      //var instance = new ShipmentTrackingApi.Address();
      //expect(instance).to.be();
    });

    it('should have the property streetSuffix (base name: "streetSuffix")', function() {
      // uncomment below and update the code to test the property streetSuffix
      //var instance = new ShipmentTrackingApi.Address();
      //expect(instance).to.be();
    });

    it('should have the property postcode (base name: "postcode")', function() {
      // uncomment below and update the code to test the property postcode
      //var instance = new ShipmentTrackingApi.Address();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new ShipmentTrackingApi.Address();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new ShipmentTrackingApi.Address();
      //expect(instance).to.be();
    });

  });

}));
