/**
 * Shipment Tracking API
 * Shipment Tracking Management provides operations to track shipments.
 *
 * The version of the OpenAPI document: 1.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ShipmentTrackingApi);
  }
}(this, function(expect, ShipmentTrackingApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ShipmentTrackingApi.ShipmentTracking();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ShipmentTracking', function() {
    it('should create an instance of ShipmentTracking', function() {
      // uncomment below and update the code to test ShipmentTracking
      //var instance = new ShipmentTrackingApi.ShipmentTracking();
      //expect(instance).to.be.a(ShipmentTrackingApi.ShipmentTracking);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ShipmentTrackingApi.ShipmentTracking();
      //expect(instance).to.be();
    });

    it('should have the property carrier (base name: "carrier")', function() {
      // uncomment below and update the code to test the property carrier
      //var instance = new ShipmentTrackingApi.ShipmentTracking();
      //expect(instance).to.be();
    });

    it('should have the property trackingCode (base name: "trackingCode")', function() {
      // uncomment below and update the code to test the property trackingCode
      //var instance = new ShipmentTrackingApi.ShipmentTracking();
      //expect(instance).to.be();
    });

    it('should have the property carrierTrackingUrl (base name: "carrierTrackingUrl")', function() {
      // uncomment below and update the code to test the property carrierTrackingUrl
      //var instance = new ShipmentTrackingApi.ShipmentTracking();
      //expect(instance).to.be();
    });

    it('should have the property trackingDate (base name: "trackingDate")', function() {
      // uncomment below and update the code to test the property trackingDate
      //var instance = new ShipmentTrackingApi.ShipmentTracking();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new ShipmentTrackingApi.ShipmentTracking();
      //expect(instance).to.be();
    });

    it('should have the property statusChangeDate (base name: "statusChangeDate")', function() {
      // uncomment below and update the code to test the property statusChangeDate
      //var instance = new ShipmentTrackingApi.ShipmentTracking();
      //expect(instance).to.be();
    });

    it('should have the property statusChangeReason (base name: "statusChangeReason")', function() {
      // uncomment below and update the code to test the property statusChangeReason
      //var instance = new ShipmentTrackingApi.ShipmentTracking();
      //expect(instance).to.be();
    });

    it('should have the property weight (base name: "weight")', function() {
      // uncomment below and update the code to test the property weight
      //var instance = new ShipmentTrackingApi.ShipmentTracking();
      //expect(instance).to.be();
    });

    it('should have the property estimatedDeliveryDate (base name: "estimatedDeliveryDate")', function() {
      // uncomment below and update the code to test the property estimatedDeliveryDate
      //var instance = new ShipmentTrackingApi.ShipmentTracking();
      //expect(instance).to.be();
    });

    it('should have the property addressFrom (base name: "addressFrom")', function() {
      // uncomment below and update the code to test the property addressFrom
      //var instance = new ShipmentTrackingApi.ShipmentTracking();
      //expect(instance).to.be();
    });

    it('should have the property addressTo (base name: "addressTo")', function() {
      // uncomment below and update the code to test the property addressTo
      //var instance = new ShipmentTrackingApi.ShipmentTracking();
      //expect(instance).to.be();
    });

    it('should have the property order (base name: "order")', function() {
      // uncomment below and update the code to test the property order
      //var instance = new ShipmentTrackingApi.ShipmentTracking();
      //expect(instance).to.be();
    });

    it('should have the property relatedCustomer (base name: "relatedCustomer")', function() {
      // uncomment below and update the code to test the property relatedCustomer
      //var instance = new ShipmentTrackingApi.ShipmentTracking();
      //expect(instance).to.be();
    });

    it('should have the property createDate (base name: "createDate")', function() {
      // uncomment below and update the code to test the property createDate
      //var instance = new ShipmentTrackingApi.ShipmentTracking();
      //expect(instance).to.be();
    });

  });

}));
